name: flutter_midi
description: A FLutter Plugin to Play midi on iOS and Android.
version: 1.1.0
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_midi

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  plugin_platform_interface: ^2.0.0
  tonic: ^0.2.3

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterMidiPlugin
      android:
        package: com.appleeducate.fluttermidi
        pluginClass: FlutterMidiPlugin
      web:
        pluginClass: FlutterMidiPlugin
        fileName: flutter_midi_web.dart
      macos:
        pluginClass: FlutterMidiPlugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ^1.3.0
